### ISSUE TITLE
Why some images’ kptsmat only has 10 dimensions instead of 11？How to reconstruct the 3D keypoints？ 

### ISSUE THREAD

**Issue by LiKrP** [JotaBravo/spacecraft-uda#12]
Hi，thanks for your nice work. The detailed preprocessed data saved me a lot of time.

I'm confused about two things.
I notice that some images’ kptsmat only has 10 dimensions instead of 11, does this has some special meaning？
I also notice that the groundtruth of the 3D kpts are very “neat”, what method did you use to reconstruct?

Thank you.

**Comment by JotaBravo** [comment]
Hi,

Can the missing keypoints occur because they fall outside the image and thus not included? I'm afraid I was not aware of this issue. I'll have a look more in detail.

Regarding the 3D keypoints. We did something similar as the process described here:

https://openaccess.thecvf.com/content_ICCVW_2019/html/R6D/Chen_Satellite_Pose_Estimation_with_Deep_Landmark_Regression_and_Nonlinear_Pose_ICCVW_2019_paper.html
